INSERT OR REPLACE INTO products (
  id, slug, name, sanskrit_name, category, tagline, description, price, mrp, offer_price, stock_count, volume, poster_image, images, dosha_affinity, in_stock, rating, review_count
) VALUES
(
  'arshana-lehyam',
  'arshana-lehyam',
  'Arshana Lehyam',
  'अर्शना अवलेह',
  'Internal Elixirs',
  'Classical Digestive Rejuvenation & Colon Harmony',
  'An authentic classical Ayurvedic jam formulated with sacred medicinal herbs and forest honey to soothe mucosal lining, stimulate Agni, and purify the digestive tract.',
  1250,
  1550,
  1250,
  85,
  '500 g / 17.6 oz',
  '/products/arshana-lehyam.png',
  '["/products/arshana-lehyam.png"]',
  'Tridoshic',
  1,
  4.9,
  142
),
(
  'rudra-tulasi',
  'rudra-tulasi',
  'Rudra Tulasi Drops',
  'रुद्र तुलसी रस',
  'Herbal Drops',
  'Panchamrit 5-Tulsi Pure Botanical Extract',
  'Hydro-distilled concentrate of five sacred Tulsi species (Rama, Krishna, Vana, Shukla, and Bisva) to fortify respiratory immunity, clear sinuses, and elevate prana.',
  499,
  650,
  499,
  120,
  '30 ml / 1.0 fl oz',
  '/products/rudra-tulasi.png',
  '["/products/rudra-tulasi.png"]',
  'Kapha',
  1,
  4.85,
  98
),
(
  'freedom-joint-care',
  'freedom-joint-care',
  'Freedom Joint Care',
  'सन्धि मुक्ति तैल',
  'Therapeutic Oils',
  '54 Botanical Synergy for Deep Musculoskeletal Ease',
  'Cold-infused restorative Ayurvedic formulation designed to deeply lubricate articular cartilage, relieve chronic joint stiffness, and restore free mobility.',
  990,
  1290,
  990,
  65,
  '200 ml / 6.8 fl oz',
  '/products/freedom.png',
  '["/products/freedom.png"]',
  'Vata',
  1,
  4.95,
  215
),
(
  'brahmi-memory-nectar',
  'brahmi-memory-nectar',
  'Brahmi Medhya Rasayana',
  'ब्राह्मी रसायन',
  'Rasayana',
  'Neurological Clarity, Cognitive Focus & Deep Sleep',
  'Sustained-release cognitive elixir infused with wild Brahmi, Shankhpushpi, and Gotu Kola to soothe neurological stress and enhance memory retention.',
  1150,
  1450,
  1150,
  40,
  '100 ml / 3.4 fl oz',
  '/products/brahmi.png',
  '["/products/brahmi.png"]',
  'Pitta',
  1,
  4.9,
  178
),
(
  'varicose-vein-elixir',
  'varicose-vein-elixir',
  'Varicose Circulation Care',
  'सिरा शुद्धि लेपम्',
  'Therapeutic Oils',
  'Vascular Tonic for Venous Strength & Micro-Flow',
  'Traditional herbal blend targeting spider veins and sluggish venous return. Strengthens endothelial walls, reduces heaviness in calves, and cools vascular heat.',
  890,
  1100,
  890,
  55,
  '100 g / 3.5 oz',
  '/products/varicose.png',
  '["/products/varicose.png"]',
  'Pitta',
  1,
  4.8,
  87
),
(
  'kumkumadi-tailam',
  'kumkumadi-tailam',
  'Kumkumadi Miraculous Beauty Fluid',
  'कुंकुमादि तैलम्',
  'Skin Radiance',
  'Kashmiri Saffron & 26 Himalayan Botanicals',
  'Cold-infused over 72 hours with pure saffron stigmas, red sandalwood, and vetiver root to revive cellular luster.',
  2499,
  2999,
  2499,
  35,
  '30 ml / 1.0 fl oz',
  'https://images.unsplash.com/photo-1608248597359-009139f4ff89?q=80&w=1000&auto=format&fit=crop',
  '["https://images.unsplash.com/photo-1608248597359-009139f4ff89?q=80&w=1000&auto=format&fit=crop"]',
  'Tridoshic',
  1,
  4.98,
  310
),
(
  'bringadi-hair-oil',
  'bringadi-hair-oil',
  'Bhringadi Intensive Scalp & Root Nectar',
  'भृङ्गामलकादि तैलम्',
  'Hair Nourishment',
  'Wild Bhringraj, Amla & Organic Sesame Base',
  'An ancient Taila Paka Vidhi formulation cooked in copper vats to stimulate follicles, halt premature greying, and cool the crown.',
  1850,
  2200,
  1850,
  70,
  '100 ml / 3.4 fl oz',
  'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=1000&auto=format&fit=crop',
  '["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=1000&auto=format&fit=crop"]',
  'Pitta',
  1,
  4.92,
  245
),
(
  'mahanarayan-tailam',
  'mahanarayan-tailam',
  'Mahanarayan Joint & Muscle Elixir',
  'महानारायण तैलम्',
  'Therapeutic Oils',
  'Ancient Taila Paka Vidhi for Deep Musculoskeletal Restoration',
  'Classical medicated oil formulated with Dashamula, Shatavari, and camphor cooked slowly to alleviate acute joint pain and pacify aggravated Vata.',
  1450,
  1750,
  1450,
  50,
  '200 ml / 6.8 fl oz',
  'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=1000&auto=format&fit=crop',
  '["https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=1000&auto=format&fit=crop"]',
  'Vata',
  1,
  4.89,
  160
);
